In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("handmade_data.csv")

In [9]:
theta = [4, 1, 2, 4, 3, 7, 2] #example thetas for testing

In [10]:
n_times = 4
n_options = 7

prices = np.zeros((n_times, n_options)) # price matrix
counts = np.zeros((n_times, n_options)) # count matrix

In [11]:
df

time  option_ID  price  count
0      0          1      2     10
1      0          2      4      2
2      0          3      6      4
3      0          5     10     11
4      0          6     12     23
5      1          2      4      8
6      1          3      6      3
7      1          4      8      2
8      1          6     12      1
9      2          1      2      6
10     2          2      4     32
11     3          1      2     66
12     3          3      6     21
13     3          5     10     19

In [12]:
# fill matrices
for index, row in df.iterrows():
    t = row['time']
    i = row['option_ID']
    prices[t][i] = row['price']
    counts[t][i] = row['count']
print("PRICES-----------")
print(prices)
print("COUNTS-----------")
print(counts)

PRICES-----------
[[ 0.  2.  4.  6.  0. 10. 12.]
 [ 0.  0.  4.  6.  8.  0. 12.]
 [ 0.  2.  4.  0.  0.  0.  0.]
 [ 0.  2.  0.  6.  0. 10.  0.]]
COUNTS-----------
[[ 0. 10.  2.  4.  0. 11. 23.]
 [ 0.  0.  8.  3.  2.  0.  1.]
 [ 0.  6. 32.  0.  0.  0.  0.]
 [ 0. 66.  0. 21.  0. 19.  0.]]


In [13]:
# calculate utility matrix
utils = np.zeros((n_times, n_options))
for t in range(0, n_times):
    for i in range(0, n_options):
        if counts[t][i] > 0:
            a = theta[i-1]
            b = theta[6]
            utils[t][i] = a + b * prices[t][i]
print("UTILS-----------")
print(utils)

UTILS-----------
[[ 0.  8.  9. 14.  0. 23. 31.]
 [ 0.  0.  9. 14. 20.  0. 31.]
 [ 0.  8.  9.  0.  0.  0.  0.]
 [ 0.  8.  0. 14.  0. 23.  0.]]


In [14]:
np.exp(utils)

array([[1.00000000e+00, 2.98095799e+03, 8.10308393e+03, 1.20260428e+06,
        1.00000000e+00, 9.74480345e+09, 2.90488497e+13],
       [1.00000000e+00, 1.00000000e+00, 8.10308393e+03, 1.20260428e+06,
        4.85165195e+08, 1.00000000e+00, 2.90488497e+13],
       [1.00000000e+00, 2.98095799e+03, 8.10308393e+03, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.98095799e+03, 1.00000000e+00, 1.20260428e+06,
        1.00000000e+00, 9.74480345e+09, 1.00000000e+00]])

In [213]:
# calculate prob matrix

# calc avg prob
avg_p = np.zeros(n_times)
for t in range(0, n_times):
    sumprob = 0
    for i in range(0, n_options):
        sumprob = sumprob + np.exp(utils[t][i])
    avg_p[t] = sumprob
print("AVG_P-----------------")
print(avg_p)
    
# calc prob matrix
probs = np.zeros((n_times, n_options))
for t in range(0, n_times):
    for i in range(0, n_options):
        probs[t][i] = np.exp(utils[t][i])/avg_p[t]
print("PROBS-----------------")
print(probs)

AVG_P-----------------
[2.90585957e+13 2.90493360e+13 1.10890419e+04 9.74600904e+09]
PROBS-----------------
[[3.44132253e-14 1.02584379e-10 2.78853253e-10 4.13854922e-08
  3.44132253e-14 3.35350116e-04 9.99664608e-01]
 [3.44241947e-14 3.44241947e-14 2.78942139e-10 4.13986840e-08
  1.67014212e-05 3.44241947e-14 9.99983257e-01]
 [9.01791163e-05 2.68820157e-01 7.30728948e-01 9.01791163e-05
  9.01791163e-05 9.01791163e-05 9.01791163e-05]
 [1.02606102e-10 3.05864480e-07 1.02606102e-10 1.23394538e-04
  1.02606102e-10 9.99876299e-01 1.02606102e-10]]


In [214]:
# build LL function
logprobs = np.log(probs)
LL = np.sum(np.multiply(counts, logprobs))
LL = (LL)
LL

-1875.9512019313697

In [25]:
word = "walk"