In [27]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("handmade_data.csv")

In [39]:
df

time  option_ID  price  count
0      0          1      2     10
1      0          2      4      2
2      0          3      6      4
3      0          5     10     11
4      0          6     12     23
5      1          2      4      8
6      1          3      6      3
7      1          4      8      2
8      1          6     12      1
9      2          1      2      6
10     2          2      4     32
11     3          1      2     66
12     3          3      6     21
13     3          5     10     19

In [40]:
theta = [0, 1, 2, 4, 3, 7, 2] #example thetas for testing

In [127]:
n_times = 4
n_options = 7

p = np.zeros((n_times, n_options)) # price matrix
c = np.zeros((n_times, n_options)) # count matrix

In [128]:
df['time'].unique()

array([0, 1, 2, 3])

In [129]:
for t in range(0, n_times):
    for i in range(0, n_options):
        #print("t", t)
        #print("i", i)
        try:
            print("t", t)
            print("i", i)
            print(df[(df['time'] == t) & (df['option_ID'] == i )].iloc[0,2])
            print(df[(df['time'] == t) & (df['option_ID'] == i )].iloc[0,3])
            p[t][i] = df[(df['time'] == t) & (df['option_ID'] == i )].iloc[0,2]
            c[t][i] = df[(df['time'] == t) & (df['option_ID'] == i )].iloc[0,3]
        except IndexError:
            pass
        

t 0
i 0
t 0
i 1
2
10
t 0
i 2
4
2
t 0
i 3
6
4
t 0
i 4
t 0
i 5
10
11
t 0
i 6
12
23
t 1
i 0
t 1
i 1
t 1
i 2
4
8
t 1
i 3
6
3
t 1
i 4
8
2
t 1
i 5
t 1
i 6
12
1
t 2
i 0
t 2
i 1
2
6
t 2
i 2
4
32
t 2
i 3
t 2
i 4
t 2
i 5
t 2
i 6
t 3
i 0
t 3
i 1
2
66
t 3
i 2
t 3
i 3
6
21
t 3
i 4
t 3
i 5
10
19
t 3
i 6


In [130]:
p

array([[ 0.,  2.,  4.,  6.,  0., 10., 12.],
       [ 0.,  0.,  4.,  6.,  8.,  0., 12.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  6.,  0., 10.,  0.]])

In [131]:
c

array([[ 0., 10.,  2.,  4.,  0., 11., 23.],
       [ 0.,  0.,  8.,  3.,  2.,  0.,  1.],
       [ 0.,  6., 32.,  0.,  0.,  0.,  0.],
       [ 0., 66.,  0., 21.,  0., 19.,  0.]])

In [21]:
# calc v values
df['v'] = None
for index, row in df.iterrows():
    df.at[index, 'v'] = theta[row['option_ID']-1] + theta[6] * row['price']
df['v'].tolist()

[4, 9, 14, 23, 31, 9, 14, 20, 31, 4, 9, 4, 14, 23]