In [27]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("handmade_data.csv")

In [39]:
df

time  option_ID  price  count
0      0          1      2     10
1      0          2      4      2
2      0          3      6      4
3      0          5     10     11
4      0          6     12     23
5      1          2      4      8
6      1          3      6      3
7      1          4      8      2
8      1          6     12      1
9      2          1      2      6
10     2          2      4     32
11     3          1      2     66
12     3          3      6     21
13     3          5     10     19

In [40]:
theta = [0, 1, 2, 4, 3, 7, 2] #example thetas for testing

In [168]:
n_times = 4
n_options = 7

prices = np.zeros((n_times, n_options)) # price matrix
counts = np.zeros((n_times, n_options)) # count matrix

In [169]:
df['time'].unique()

array([0, 1, 2, 3])

In [170]:
# fill matrices
for index, row in df.iterrows():
    t = row['time']
    i = row['option_ID']
    prices[t][i] = row['price']
    counts[t][i] = row['count']

In [174]:
# calculate utility matrix
util = np.zeros((n_times, n_options))
for t in range(0, n_times):
    for i in range(0, n_options):
        if counts[t][i] > 0:
            a = theta[i-1]
            b = theta[6]
            util[t][i] = a + b * prices[t][i]

In [175]:
util

array([[ 0.,  4.,  9., 14.,  0., 23., 31.],
       [ 0.,  0.,  9., 14., 20.,  0., 31.],
       [ 0.,  4.,  9.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0., 14.,  0., 23.,  0.]])

In [180]:
# calculate prob matrix
avgs = np.zeros(n_times)
for t in range(0, n_times):
    sumprob = 0
    for i in range(0, n_options):
        sumprob = sumprob + np.exp(util[t][i])
    avgs[t] = sumprob
print(avgs)

[2.90585957e+13 2.90493360e+13 8.16268208e+03 9.74600611e+09]


In [21]:
# calc v values
df['v'] = None
for index, row in df.iterrows():
    df.at[index, 'v'] = theta[row['option_ID']-1] + theta[6] * row['price']
df['v'].tolist()

[4, 9, 14, 23, 31, 9, 14, 20, 31, 4, 9, 4, 14, 23]