In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("handmade_data.csv")

In [3]:
df

time  option_ID  price  count
0      0          1      2     10
1      0          2      4      2
2      0          3      6      4
3      0          5     10     11
4      0          6     12     23
5      1          2      4      8
6      1          3      6      3
7      1          4      8      2
8      1          6     12      1
9      2          1      2      6
10     2          2      4     32
11     3          1      2     66
12     3          3      6     21
13     3          5     10     19

In [4]:
theta = [1, 1, 1, 1, 1, 1, 1] #example thetas for testing

In [5]:
n_times = 4
n_options = 7

prices = np.zeros((n_times, n_options)) # price matrix
counts = np.zeros((n_times, n_options)) # count matrix

In [6]:
# fill matrices
for index, row in df.iterrows():
    t = row['time']
    i = row['option_ID']
    prices[t][i] = row['price']
    counts[t][i] = row['count']
print("PRICES-----------")
print(prices)
print("COUNTS-----------")
print(counts)

PRICES-----------
[[ 0.  2.  4.  6.  0. 10. 12.]
 [ 0.  0.  4.  6.  8.  0. 12.]
 [ 0.  2.  4.  0.  0.  0.  0.]
 [ 0.  2.  0.  6.  0. 10.  0.]]
COUNTS-----------
[[ 0. 10.  2.  4.  0. 11. 23.]
 [ 0.  0.  8.  3.  2.  0.  1.]
 [ 0.  6. 32.  0.  0.  0.  0.]
 [ 0. 66.  0. 21.  0. 19.  0.]]


In [231]:
# calculate utility matrix
utils = np.zeros((n_times, n_options))
for t in range(0, n_times):
    for i in range(0, n_options):
        if counts[t][i] > 0:
            a = theta[i-1]
            b = theta[6]
            utils[t][i] = a + b * prices[t][i]
print("UTILS-----------")
print(utils)

UTILS-----------
[[ 0.  3.  5.  7.  0. 11. 13.]
 [ 0.  0.  5.  7.  9.  0. 13.]
 [ 0.  3.  5.  0.  0.  0.  0.]
 [ 0.  3.  0.  7.  0. 11.  0.]]


In [232]:
# calculate prob matrix

# calc avg prob
avg_p = np.zeros(n_times)
for t in range(0, n_times):
    sumprob = 0
    for i in range(0, n_options):
        sumprob = sumprob + np.exp(utils[t][i])
    avg_p[t] = sumprob
print("AVG_P-----------------")
print(avg_p)
    
# calc prob matrix
probs = np.zeros((n_times, n_options))
for t in range(0, n_times):
    for i in range(0, n_options):
        probs[t][i] = np.exp(utils[t][i])/avg_p[t]
print("PROBS-----------------")
print(probs)

AVG_P-----------------
[5.03554666e+05 4.51764522e+05 1.73498696e+02 6.09948604e+04]
PROBS-----------------
[[1.98588171e-06 3.98875004e-05 2.94730978e-04 2.17778373e-03
  1.98588171e-06 1.18902963e-01 8.78580663e-01]
 [2.21354257e-06 2.21354257e-06 3.28518845e-04 2.42744418e-03
  1.79365212e-02 2.21354257e-06 9.79300875e-01]
 [5.76373208e-03 1.15767653e-01 8.55413686e-01 5.76373208e-03
  5.76373208e-03 5.76373208e-03 5.76373208e-03]
 [1.63948240e-05 3.29298842e-04 1.63948240e-05 1.79791076e-02
  1.63948240e-05 9.81626014e-01 1.63948240e-05]]


In [233]:
# build LL function
logprobs = np.log(probs)
LL = -np.sum(np.multiply(counts, logprobs))
LL = (LL)
LL

890.6654276720102